lines 40
columns 80
edge top
background_opacity 0.75
hide_on_focus_loss no
grab_keyboard no
margin_left 8
margin_right 8
margin_top 16
margin_bottom 0
kitty_conf /home/cwinters/.config/kitty/kitty.conf
app_id kitty-quick-access
output_name DP-1
start_as_hidden no
focus_policy exlcusive
